spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/grocery_store
    username: root
  jpa:
    hibernate.ddl.auto: create
    generate-ddl: true
    show-sql: true


